### ISSUE TITLE
Display name should be the wrapped component's name

### ISSUE THREAD

**Issue by danmartinez101** [gaearon/react-proxy#5]
So that instead of:
`Warning: Failed propType: Required prop 'onUpdateEmail' was not specified in 'HotClass'. Check the render method of 'HotClass'.`
the developer sees:
`Warning: Failed propType: Required prop 'onUpdateEmail' was not specified in 'WrappedComponentName'. Check the render method of 'WrappedComponentName'.`

**Comment by gaearon** [comment]
Done in master.

**Comment by okonet** [comment]
Is this already in 1.0? I'm still getting this with `react-transform-webpack-hmr`

**Comment by gaearon** [comment]
@okonet Please see https://github.com/gaearon/babel-plugin-react-transform/pull/21: you need to use `babel-plugin-react-display-name` with it.

**Comment by okonet** [comment]
Thank you for a quick reply! I'll try it right away.

**Comment by okonet** [comment]
Worked like a charm! :heart_eyes:

**Comment by gaearon** [comment]
Glad to hear that!
