### ISSUE TITLE
core-js WeakMaps are broken on React Native?

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-proxy#50]
As reported [here](https://github.com/gaearon/react-proxy/pull/45#issuecomment-192885650) by @davodesign84 and [here](http://stackoverflow.com/q/35822104/458193), it appears that #45 broke React Native because for some reason `WeakMap` polyfill from `core-js` returns `undefined`:

```
undefined is not a constructor (evaluating 'new _weakMap2.default()')
```

Alas, I don’t have React Native at hand and can’t look into why this happens. We just use it like this:

```js
import WeakMap from 'core-js/library/es6/weak-map';
```

I’ll be grateful if anybody can look into why this fails on RN. Possible alternatives:

* Use a different `WeakMap` polyfill
* Use a `Map` polyfill instead of the issue is specific to `WeakMap`

**Comment by gaearon** [comment]
@davodesign84 Are you up for helping me test different fixes?

**Comment by gaearon** [comment]
I’m trying to install React Native but it’s been 30 minutes and I have no idea what the progress is because there is no spinner. :-/

**Comment by davodesign84** [comment]
Sure, I can try!

**Comment by gaearon** [comment]
Can you put `console.log(_weakMap2)` before the failing line and check what’s there?

**Comment by gaearon** [comment]
So far I haven’t been able to reproduce this with React Native 0.21.

* Are you using React Native as is, or via something like `react-native-webpack-server`?
* Are you using it with Parse as described in http://stackoverflow.com/questions/35822104/react-native-weakmap2-error?

**Comment by davodesign84** [comment]
Yes I am.

Here is what comes out with the console debug: 

createClassProxy.js:53Object {default: undefined}

**Comment by gaearon** [comment]
OK, I repro’d it after including Parse. :+1: 
Let me look into this.

**Comment by gaearon** [comment]
Apparently the version we import stops working if some other package (in this case, Parse) imports `WeakMap` from `core-js` in `babel-runtime@5.x`. Not sure how to fix this.

**Comment by satya164** [comment]
I don't think we include `babel-polyfill` in React Native. So `WeakMap` might not be there,

**Comment by gaearon** [comment]
It’s not but I’m directly importing `core-js` polyfill. It works fine *unless* some other package *also* imports core-js polyfill at which point it stops working.

**Comment by satya164** [comment]
@gaearon Ah. That makes sense. Is it possible that the Babel transforms enabled can affect this? Here are the ones enabled in React Native - https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js

**Comment by gaearon** [comment]
Hard to say. My guess would rather be that `core-js` 1.x and 2.x WeakMaps are incompatible but it’s, too, a shot in the dark. Maybe @zloyrock has insights.

**Comment by zloirock** [comment]
> @zloyrock

@zloirock :)

> `core-js` 1.x and 2.x WeakMaps are incompatible

They are compatible.

> That makes sense. Is it possible that the Babel transforms enabled can affect this?

It's possible - `babel` `runtime` transformer should not transform `core-js`.

Without a reproducible example, I have no any other ideas.

**Comment by gaearon** [comment]
Thanks for chiming in :+1: 

I’m trying to come up with reproducible example but there are many variables that come into play (e.g. hot reloading was recently added to RN which will import that WeakMap as part of initialization code) so it’s a bit hard to isolate the offending behavior.

**Comment by davodesign84** [comment]
Is it related to this? https://github.com/facebook/react-native/pull/5294

**Comment by gaearon** [comment]
I wouldn’t expect it to be.

**Comment by gaearon** [comment]
Steps to reproduce:

1. Create a new project with RN 0.21
2. `npm install --save parse`
3. Add `require("parse/react-native")`
4. Boom!

The crash happens because `import 'core-js/library/es6/weak-map` inside `react-proxy` code starts returning `undefined` *if and only if* `parse/react-native` is also imported.

Relevant code in `react-proxy` (using core-js 2.x):

```js
var _weakMap = require('core-js/library/es6/weak-map');
var _weakMap2 = _interopRequireDefault(_weakMap);
var allProxies = new _weakMap2.default(); // crashes

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

Relevant code in `parse/react-native` (using core-js 1.x):

```js
var _WeakMap = require('babel-runtime/core-js/weak-map')['default'];
var objectState = new _WeakMap();
```

**Comment by gaearon** [comment]
Some more info.

First, disable hot reloading by removing `require('react-transform-hmr');` from `InitializeJavaScriptAppEngine.js`. This way we can get a cleaner picture of what’s going on.

Now try a few things in your `index.ios.js`:

```js
// works
require('react-transform-hmr')
```

vs

```js
// works
require('babel-runtime/core-js/weak-map')
require('react-transform-hmr')
```

vs

```js
// fails!
require('react-transform-hmr')
require('babel-runtime/core-js/weak-map')
```


Apparently importing `babel-runtime/core-js/weak-map` **after `react-transform-hmr`** somehow messes up import of `core-js/library/es6/weak-map` **inside** `react-transform-hmr`.

However, if we import  `core-js/library/es6/weak-map` **itself** inside `index.ios.js`, there is no problem:

```js
// works
require('babel-runtime/core-js/weak-map')
if (typeof require('core-js/library/es6/weak-map') !== 'function') {
  throw new Error('Foo')
}
```

I’m very puzzled by this. I could not replicate this on the web so I would assume a packager issue or something related to transforms.

**Comment by gaearon** [comment]
Trimmed it down to this:

```js
if (typeof require('react-proxy/node_modules/core-js/library/es6/weak-map') !== 'function') {
  throw new Error('why u no function')
}
// require('babel-runtime/core-js/weak-map') <-- UNCOMMENT AND IT'LL CRASH
```

In this case `'react-proxy/node_modules/core-js` is 2.x and `babel-runtime` is 5.8.35, and keeps `core-js` as a folder internally.

**Comment by davodesign84** [comment]
Thanks @gaearon that's impressively quick! So commenting that line should fix the issue?

**Comment by gaearon** [comment]
No, that’s not really a line in anyone’s code (well, technically it’s Parse’s line but their usage is correct).
I trimmed down the simplest case to reproduce but it’s still an issue—maybe in Packager, or maybe somewhere else.

**Comment by gaearon** [comment]
This rabbit hole is too deep. I’m giving up and removing `WeakMap` usage as it wasn’t paramount in our case.

**Comment by gaearon** [comment]
Fixed in 1.1.7.

**Comment by davodesign84** [comment]
Fantastic, thanks @gaearon !
